name: PatchTest
main: com.i0dev.plugin.patchtest.PatchTestPlugin
version: 1.0.0
author: i01
description: An entire gamemode that you can practice patching against a replicated cannon.
website: www.i0dev.com
depend:
  - WorldEdit
softdepend:
  - PlaceHolderAPI
commands:
  patch:
    aliases:
      - patchtest
      - pt
    description: The main patchtest command
    usage: /patch [create/start/invite/join/help/reload/version]
  obby:
    aliases:
      - freeObsidian
      - freeObby
      - obbyfill
    description: Opens an inventory full of obsidian.
    usage: /obby
  leaderboard:
    aliases:
      - lb
      - leaderb
      - stats
    description: Opens an leaderboard GUI
    usage: /leaderboard


permissions:
  patchtest.create:
    description: Use the /patch create command
    default: not op
  patchtest.start:
    description: Use the /patch start command
    default: not op
  patchtest.invite:
    description: Use the /patch invite command
    default: not op
  patchtest.remove:
    description: Use the /patch remove command
    default: not op
  patchtest.join:
    description: Use the /patch join command
    default: not op
  patchtest.leave:
    description: Use the /patch leave command
    default: not op
  patchtest.admin:
    description: Bypasses many restrictions
    default: op
  patchtest.reload:
    description: Use the /patch reload command
    default: op
  patchtest.obby:
    description: Use the /obby command
    default: not op
  patchtest.leaderboard:
    description: Use the /leaderboard
    default: not op