name: PatchTest
main: com.i0dev.plugin.patchtest.PatchTestPlugin
version: 1.0.0
author: i01
description: An entire gamemode that you can practice patching against a replicated cannon.
website: www.i0dev.com
depend:
  - WorldEdit
softdepend:
  - PlaceHolderAPI
commands:
  patch:
    aliases:
      - patchtest
      - pt
    description: The main patchtest command
    usage: /patch [create/start/invite/join/help/reload/version]
  party:
    aliases:
      - p
    description: The main party command
  obby:
    aliases:
      - freeObsidian
      - freeObby
      - obbyfill
    description: Opens an inventory full of obsidian.
    usage: /obby
  leaderboard:
    aliases:
      - lb
      - leaderb
      - stats
    description: Opens an leaderboard GUI
    usage: /leaderboard
  session:
    aliases:
      - ses
      - sesh
      - patchsession
    description: session commands
